[package]
name = "deathloop"
version = "0.1.0"
authors = ["Evangelos Michelioudakis <vagmcs@gmail.com>"]
edition = "2021"
description = "A reinforcement learning library"
documentation = "https://docs.rs/deathloop"
readme = "README.md"
repository = "https://github.com/vagmcs/deathloop"
license = "MIT"
keywords = ["ai", "machine-learning", "reinforcement"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
