name: Tester

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  check:
    if: always()
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - name: Check whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}